# Generated by Django 3.1.7 on 2022-07-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='Nashville', max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(default='TN', max_length=2),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
