# Generated by Django 3.1.7 on 2022-07-31 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20220731_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='buisness_name',
            new_name='title',
        ),
    ]
