# Generated by Django 3.1.7 on 2022-08-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20220731_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
