# Generated by Django 3.1.7 on 2022-08-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
