# Generated by Django 3.2.13 on 2022-11-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_location_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
