# Generated by Django 3.2.13 on 2022-11-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0007_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(default='Nashville', max_length=100)),
                ('state', models.CharField(default='TN', max_length=2)),
                ('zipcode', models.CharField(max_length=5, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
