# Generated by Django 3.1.7 on 2022-07-29 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merch',
            old_name='name',
            new_name='title',
        ),
    ]
