# Generated by Django 3.1.7 on 2022-07-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20220729_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merch',
            old_name='images',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='merch',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='merch',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
