# Generated by Django 3.1.7 on 2022-08-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
