# Generated by Django 3.1.7 on 2022-08-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
