# Generated by Django 3.1.7 on 2022-08-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0007_auto_20220807_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
