# Generated by Django 3.2.13 on 2022-11-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0009_auto_20221007_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='merch',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='merch',
            name='image_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='merch',
            name='image_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merch.merch')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merch.size')),
            ],
        ),
        migrations.AddField(
            model_name='merch',
            name='sizes',
            field=models.ManyToManyField(through='merch.ProductSize', to='merch.Size'),
        ),
    ]
