# Generated by Django 3.2.13 on 2022-11-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0010_auto_20221109_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=5),
        ),
    ]
