# Generated by Django 3.2.13 on 2022-11-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0015_alter_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(default='l', max_length=50),
        ),
    ]
