# Generated by Django 3.2.13 on 2022-11-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0016_alter_size_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merch',
            old_name='sizes',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='l', max_length=50),
        ),
    ]
