# Generated by Django 3.2.13 on 2022-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0017_auto_20221109_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
