# Generated by Django 3.2.13 on 2022-11-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0020_alter_size_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merch',
            old_name='size',
            new_name='sizes',
        ),
    ]
