# Generated by Django 3.2.13 on 2022-11-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0021_rename_size_merch_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='sizes',
        ),
        migrations.AddField(
            model_name='merch',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merch.productsize'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merch.merch', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='l', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
