# Generated by Django 3.2.13 on 2022-11-09 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0022_auto_20221109_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='l', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='merch',
            name='size',
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merch.merch'),
        ),
        migrations.AddField(
            model_name='merch',
            name='sizes',
            field=models.ManyToManyField(through='merch.ProductSize', to='merch.Size'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merch.size'),
        ),
    ]
