# Generated by Django 3.2.13 on 2022-11-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0023_auto_20221109_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='sizes',
            field=models.ManyToManyField(to='merch.ProductSize'),
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='l', max_length=50),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
