# Generated by Django 3.2.13 on 2022-11-10 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0024_auto_20221110_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='sizes',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], default='l', max_length=50),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='merch.merch'),
        ),
    ]
