# Generated by Django 3.2.13 on 2022-11-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0025_auto_20221110_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='s', max_length=50),
        ),
    ]
