# Generated by Django 3.1.7 on 2022-09-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_guestartist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestartist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='guestartist',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='guestartist',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='guestartist',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='guestartist',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='guestartist',
            name='image_5',
        ),
        migrations.AddField(
            model_name='guestartist',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guestartist',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
