# Generated by Django 3.1.7 on 2022-09-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20220911_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestartist',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
