# Generated by Django 3.2.13 on 2022-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_auto_20221105_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_name',
        ),
        migrations.AddField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
