# Generated by Django 3.2.13 on 2022-11-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_artist_apprentice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='image_10',
            new_name='image_0',
        ),
    ]
