# Generated by Django 3.2.13 on 2022-12-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_rename_image_10_artist_image_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='insta_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
