# Generated by Django 3.2.13 on 2022-12-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_artist_insta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
